
backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Property Index"
        name: "property_index"
        file: "properties/index.json" # This creates a list of all filenames
        fields:
          - {label: "All Properties", name: "all", widget: "list", field: {label: "File Name", name: "filename", widget: "string"}}
  - name: "properties"
    # ... keep your existing properties collection below this